networks:
  roboshop:
    driver: bridge

services:
  mongodb:
    image: saikiranreddy11/mongodb:v1
    container_name: mongodb
    volumes:
      mongodb:
        - source: mongodb
          target: /data/db
          type: volume
      networks:
    -   - roboshop
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      mongodb:
        - source: redis
          target: /usr/local/etc/redis
          type: volume
    networks:
    - roboshop
  mysql:
    image: saikiranreddy11/mysql:v1
    container_name: mysql
    volumes:
      mongodb:
        - source: mysql
          target: /var/lib/mysql
          type: volume
    networks:
      - roboshop
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      mongodb:
        - source: rabbitmq
          target: /var/lib/rabbitmq
          type: volume
    networks:
      - roboshop
  catalogue:
    image: saikiranreddy11/catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb
  user:
    image: saikiranreddy11/user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - catalogue
  cart:
    image: saikiranreddy11/cart:v1
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - redis
      - catalogue
  shipping:
    image: saikiranreddy11/shipping:v1
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - cart
      - mysql

  payment:
    image: saikiranreddy11/payment:v1
    container_name: payment
    networks:
      - roboshop
    depends_on:
      - cart
      - user
      - rabbitmq
  
  
  web:
    image: saikiranreddy11/web:v1
    container_name: web
    networks:
      - roboshop
    depends_on:
      - catalogue
      - user
    ports:
      - "80:80"
