networks:
  roboshop:

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    networks:
    - roboshop
  redis:
    image: redis:latest
    container_name: redis
    networks:
    - roboshop
  mysql:
    image: mysql:v1
    container_name: mysql
    networks:
      - roboshop
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb
  user:
    image: user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - catalogue
  cart:
    image: cart:v1
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - redis
      - catalogue
  shipping:
    image: shipping:v1
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - cart
      - mysql
  
  web:
    image: web:v1
    container_name: web
    networks:
      - roboshop
    depends_on:
      - catalogue
      - user
    ports:
      - "80:80"
