networks:
  roboshop:

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    networks:
    - roboshop
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb
  user:
    image: user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - catalogue
  web:
    image: web:v1
    container_name: web
    networks:
      - roboshop
    depends_on:
      - catalogue
      - user
